#tomcat
server:
  port: 8080

#spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
    #druid
    type: com.alibaba.druid.pool.DruidDataSource
    
#mybatis
mybatis:
  #实体类的包
  type-aliases-package: com.example.demo.entity
  #mapper对应的xml文件
  mapper-locations: classpath:mapping/*.xml
 